name: Automated Unit Tests

on: [push]

env:
  CI: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run lint

  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run test:unit:ci

  build:
    needs: [lint, test]
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run build

  e2e:
    name: End to End Testing
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run test:e2e:ci
