name: Automated Unit Tests

on: [push]

env:
  CI: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm clean-install
    - run: npm run lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm clean-install
    - run: npm run test:unit:ci

  build:
    needs: [lint, test]
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm clean-install
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist

  e2e:
    name: End to End Testing
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm clean-install
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist
    - run: npm run test:e2e:ci

  lighthouseci:
    name: Lighthouse CI performance budget
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm clean-install
    - run: npm install -g @lhci/cli
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist
    - run: lhci autorun
